package edu.toppin.todolist

import androidx.room.Entity
import androidx.room.PrimaryKey

@Entity(tableName = "item_table")
data class Item(
    @PrimaryKey(autoGenerate = true) val id: Int = 0,
    val name: String,
    val description: String,
    val isChecked: Boolean
)

//The @Entity annotation indicates that this class represents a table.
//@PrimaryKey(autoGenerate = true) means the id will be autogenerated for each entry.
